### ISSUE TITLE
Enable/Disable features of stack

### ISSUE THREAD

**Issue by CoderOnWinks** [embedded-office/canopen-stack#49]
Hi,

Is it possible to enable/disable some of the features of canopen-stack. I am considering not to use NMT, LSS slave. Can i configure them not to build in stack. Please suggest.

Thanks

**Comment by michael-hillmann** [comment]
I recommend building a library out of the CANopen stack files. When using the stack, the linker will ensure that only the required functions are included in your image.

**Comment by Domen2242** [comment]
I would also be interested in such a feature as my application is based only on CiA 301. CiA 305's LSS can't be excluded by the linker because it is used in the CONodeProcess function. 
Maybe something like a "#define USE_LSS 1" could be added to the config, which would enable us to save on program space and execution time when we don't to use a feature.
I have created a pull request with my implementation.
