### ISSUE TITLE
bug in co_nvm_sim

### ISSUE THREAD

**Issue by florenso** [embedded-office/canopen-stack#93]
The loop in DrvNvmRead and DrvNvmWrite is incorrect.
I think its dead "example" code, but you might break some test code in the future.

`while ((pos < NVM_SIM_SIZE) && (size > 0))`
should be
`while ((pos < NVM_SIM_SIZE) && (size > idx))`

Offtopic: this seems like a very solid implementation and properly documented stack! thx for sharing.

**Comment by michael-hillmann** [comment]
Hi thank you for your issue. You are right, the loop is not correct. The looping of `pos` is correctly through the size of the available NVM memory - but the `size`, which is looping through the size of the given buffer is missing the decrement statement in the while loop:

```c
static uint32_t DrvNvmRead(uint32_t start, uint8_t *buffer, uint32_t size)
{
    uint32_t idx = 0;
    uint32_t pos;

    idx = 0;
    pos = start;
    while ((pos < NVM_SIM_SIZE) && (size > 0)) {
        buffer[idx] = NvmMemory[pos];
        idx++;
        pos++;
        size--;      /* <<<< that was the intension - but missing <<<< */
    }

    return (idx);
}
```

Note: I think, your solution is the better one. I would change it slightly, because it's easier for me to follow the code while reading when we use the constant values at the right side of a relation:

`while ((pos < NVM_SIM_SIZE) && (idx < size)) {`
